version: "3"

services:
  pixmodels:
    build:
      context: .
      dockerfile: conf/nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - vol_pixmodels:/var/www/html/pixmodels
  php:
    build:
      context: .
      dockerfile: conf/php/Dockerfile
    networks:
      - internal
    volumes:
      - vol_pixmodels:/var/www/html/pixmodels

volumes:
  vol_pixmodels:

networks:
  internal:
    driver: bridge